// utils/currencyMetadata.ts

interface CurrencyMeta {
    label: string;
    symbol: string;
}

export const currencyMetadata: { [code: string]: CurrencyMeta } = {
    AED: { label: 'United Arab Emirates Dirham', symbol: 'د.إ' },
    AFN: { label: 'Afghan Afghani', symbol: '؋' },
    ALL: { label: 'Albanian Lek', symbol: 'L' },
    AMD: { label: 'Armenian Dram', symbol: '֏' },
    ANG: { label: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
    AOA: { label: 'Angolan Kwanza', symbol: 'Kz' },
    ARS: { label: 'Argentine Peso', symbol: '$' },
    AUD: { label: 'Australian Dollar', symbol: '$' },
    AWG: { label: 'Aruban Florin', symbol: 'ƒ' },
    AZN: { label: 'Azerbaijani Manat', symbol: '₼' },
    BAM: { label: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM' },
    BBD: { label: 'Barbadian Dollar', symbol: '$' },
    BDT: { label: 'Bangladeshi Taka', symbol: '৳' },
    BGN: { label: 'Bulgarian Lev', symbol: 'лв' },
    BHD: { label: 'Bahraini Dinar', symbol: '.د.ب' },
    BIF: { label: 'Burundian Franc', symbol: 'FBu' },
    BMD: { label: 'Bermudian Dollar', symbol: '$' },
    BND: { label: 'Brunei Dollar', symbol: '$' },
    BOB: { label: 'Bolivian Boliviano', symbol: 'Bs.' },
    BRL: { label: 'Brazilian Real', symbol: 'R$' },
    BSD: { label: 'Bahamian Dollar', symbol: '$' },
    BTN: { label: 'Bhutanese Chhertum', symbol: 'Nu.' },
    BWP: { label: 'Botswana Pula', symbol: 'P' },
    BYN: { label: 'Belarusian Ruble', symbol: 'Br' },
    BZD: { label: 'Belize Dollar', symbol: '$' },
    CAD: { label: 'Canadian Dollar', symbol: '$' },
    CDF: { label: 'Congolese Franc', symbol: 'FC' },
    CHF: { label: 'Swiss Franc', symbol: 'CHF' },
    CLP: { label: 'Chilean Peso', symbol: '$' },
    CNY: { label: 'Chinese Yuan', symbol: '¥' },
    COP: { label: 'Colombian Peso', symbol: '$' },
    CRC: { label: 'Costa Rican Colón', symbol: '₡' },
    CUC: { label: 'Cuban Convertible Peso', symbol: '$' },
    CUP: { label: 'Cuban Peso', symbol: '₱' },
    CVE: { label: 'Cape Verdean Escudo', symbol: 'Esc' },
    CZK: { label: 'Czech Koruna', symbol: 'Kč' },
    DJF: { label: 'Djiboutian Franc', symbol: 'Fdj' },
    DKK: { label: 'Danish Krone', symbol: 'kr' },
    DOP: { label: 'Dominican Peso', symbol: 'RD$' },
    DZD: { label: 'Algerian Dinar', symbol: 'د.ج' },
    EGP: { label: 'Egyptian Pound', symbol: '£' },
    ERN: { label: 'Eritrean Nakfa', symbol: 'Nfk' },
    ETB: { label: 'Ethiopian Birr', symbol: 'Br' },
    EUR: { label: 'Euro', symbol: '€' },
    FJD: { label: 'Fijian Dollar', symbol: '$' },
    FKP: { label: 'Falkland Islands Pound', symbol: '£' },
    FOK: { label: 'Faroese Króna', symbol: 'kr' },
    GBP: { label: 'British Pound', symbol: '£' },
    GEL: { label: 'Georgian Lari', symbol: '₾' },
    GGP: { label: 'Guernsey Pound', symbol: '£' },
    GHS: { label: 'Ghanaian Cedi', symbol: '₵' },
    GIP: { label: 'Gibraltar Pound', symbol: '£' },
    GMD: { label: 'Gambian Dalasi', symbol: 'D' },
    GNF: { label: 'Guinean Franc', symbol: 'FG' },
    GTQ: { label: 'Guatemalan Quetzal', symbol: 'Q' },
    GYD: { label: 'Guyanese Dollar', symbol: '$' },
    HKD: { label: 'Hong Kong Dollar', symbol: '$' },
    HNL: { label: 'Honduran Lempira', symbol: 'L' },
    HRK: { label: 'Croatian Kuna', symbol: 'kn' },
    HTG: { label: 'Haitian Gourde', symbol: 'G' },
    HUF: { label: 'Hungarian Forint', symbol: 'Ft' },
    IDR: { label: 'Indonesian Rupiah', symbol: 'Rp' },
    ILS: { label: 'Israeli Shekel', symbol: '₪' },
    IMP: { label: 'Manx Pound', symbol: '£' },
    INR: { label: 'Indian Rupee', symbol: '₹' },
    IQD: { label: 'Iraqi Dinar', symbol: 'ع.د' },
    IRR: { label: 'Iranian Rial', symbol: '﷼' },
    ISK: { label: 'Icelandic Króna', symbol: 'kr' },
    JEP: { label: 'Jersey Pound', symbol: '£' },
    JMD: { label: 'Jamaican Dollar', symbol: '$' },
    JOD: { label: 'Jordanian Dinar', symbol: 'د.أ' },
    JPY: { label: 'Japanese Yen', symbol: '¥' },
    KES: { label: 'Kenyan Shilling', symbol: 'Ksh' },
    KGS: { label: 'Kyrgyzstani Som', symbol: 'с' },
    KHR: { label: 'Cambodian Riel', symbol: '៛' },
    KID: { label: 'Kiribati Dollar', symbol: '$' },
    KMF: { label: 'Comorian Franc', symbol: 'FC' },
    KRW: { label: 'South Korean Won', symbol: '₩' },
    KWD: { label: 'Kuwaiti Dinar', symbol: 'د.ك' },
    KYD: { label: 'Cayman Islands Dollar', symbol: '$' },
    KZT: { label: 'Kazakhstani Tenge', symbol: '₸' },
    LAK: { label: 'Laotian Kip', symbol: '₭' },
    LBP: { label: 'Lebanese Pound', symbol: 'ل.ل' },
    LKR: { label: 'Sri Lankan Rupee', symbol: '₨' },
    LRD: { label: 'Liberian Dollar', symbol: '$' },
    LSL: { label: 'Lesotho Loti', symbol: 'L' },
    LYD: { label: 'Libyan Dinar', symbol: 'ل.د' },
    MAD: { label: 'Moroccan Dirham', symbol: 'د.م.' },
    MDL: { label: 'Moldovan Leu', symbol: 'L' },
    MGA: { label: 'Malagasy Ariary', symbol: 'Ar' },
    MKD: { label: 'Macedonian Denar', symbol: 'ден' },
    MMK: { label: 'Myanmar Kyat', symbol: 'K' },
    MNT: { label: 'Mongolian Tögrög', symbol: '₮' },
    MOP: { label: 'Macanese Pataca', symbol: 'MOP$' },
    MRU: { label: 'Mauritanian Ouguiya', symbol: 'UM' },
    MUR: { label: 'Mauritian Rupee', symbol: '₨' },
    MVR: { label: 'Maldivian Rufiyaa', symbol: 'ރ.' },
    MWK: { label: 'Malawian Kwacha', symbol: 'MK' },
    MXN: { label: 'Mexican Peso', symbol: '$' },
    MYR: { label: 'Malaysian Ringgit', symbol: 'RM' },
    MZN: { label: 'Mozambican Metical', symbol: 'MT' },
    NAD: { label: 'Namibian Dollar', symbol: '$' },
    NGN: { label: 'Nigerian Naira', symbol: '₦' },
    NIO: { label: 'Nicaraguan Córdoba', symbol: 'C$' },
    NOK: { label: 'Norwegian Krone', symbol: 'kr' },
    NPR: { label: 'Nepalese Rupee', symbol: '₨' },
    NZD: { label: 'New Zealand Dollar', symbol: '$' },
    OMR: { label: 'Omani Rial', symbol: 'ر.ع.' },
    PAB: { label: 'Panamanian Balboa', symbol: 'B/.' },
    PEN: { label: 'Peruvian Sol', symbol: 'S/.' },
    PGK: { label: 'Papua New Guinean Kina', symbol: 'K' },
    PHP: { label: 'Philippine Peso', symbol: '₱' },
    PKR: { label: 'Pakistani Rupee', symbol: '₨' },
    PLN: { label: 'Polish Złoty', symbol: 'zł' },
    PYG: { label: 'Paraguayan Guarani', symbol: '₲' },
    QAR: { label: 'Qatari Riyal', symbol: 'ر.ق' },
    RON: { label: 'Romanian Leu', symbol: 'lei' },
    RSD: { label: 'Serbian Dinar', symbol: 'дин.' },
    RUB: { label: 'Russian Ruble', symbol: '₽' },
    RWF: { label: 'Rwandan Franc', symbol: 'FRw' },
    SAR: { label: 'Saudi Riyal', symbol: 'ر.س' },
    SBD: { label: 'Solomon Islands Dollar', symbol: '$' },
    SCR: { label: 'Seychellois Rupee', symbol: '₨' },
    SDG: { label: 'Sudanese Pound', symbol: '£' },
    SEK: { label: 'Swedish Krona', symbol: 'kr' },
    SGD: { label: 'Singapore Dollar', symbol: '$' },
    SHP: { label: 'Saint Helena Pound', symbol: '£' },
    SLE: { label: 'Sierra Leonean Leone', symbol: 'Le' },
    SLL: { label: 'Sierra Leonean Leone', symbol: 'Le' },
    SOS: { label: 'Somali Shilling', symbol: 'Sh' },
    SRD: { label: 'Surinamese Dollar', symbol: '$' },
    SSP: { label: 'South Sudanese Pound', symbol: '£' },
    STN: { label: 'São Tomé and Principe Dobra', symbol: 'Db' },
    SYP: { label: 'Syrian Pound', symbol: '£' },
    SZL: { label: 'Swazi Lilangeni', symbol: 'L' },
    THB: { label: 'Thai Baht', symbol: '฿' },
    TJS: { label: 'Tajikistani Somoni', symbol: 'ЅМ' },
    TMT: { label: 'Turkmenistan Manat', symbol: 'T' },
    TND: { label: 'Tunisian Dinar', symbol: 'د.ت' },
    TOP: { label: 'Tongan Paʻanga', symbol: 'T$' },
    TRY: { label: 'Turkish Lira', symbol: '₺' },
    TTD: { label: 'Trinidad and Tobago Dollar', symbol: '$' },
    TVD: { label: 'Tuvaluan Dollar', symbol: '$' },
    TWD: { label: 'New Taiwan Dollar', symbol: '$' },
    TZS: { label: 'Tanzanian Shilling', symbol: 'TSh' },
    UAH: { label: 'Ukrainian Hryvnia', symbol: '₴' },
    UGX: { label: 'Ugandan Shilling', symbol: 'USh' },
    USD: { label: 'United States Dollar', symbol: '$' },
    USN: { label: 'United States Dollar (next day)', symbol: '$' },
    UYI: { label: 'Uruguay Peso en Unidades Indexadas (URUIURUI)', symbol: '$U' },
    UYU: { label: 'Uruguayan Peso', symbol: '$U' },
    UZS: { label: 'Uzbekistan Som', symbol: 'so\'m' },
    VES: { label: 'Venezuelan Bolivar', symbol: 'Bs' },
    VND: { label: 'Vietnamese Dong', symbol: '₫' },
    VUV: { label: 'Vanuatu Vatu', symbol: 'VT' },
    WST: { label: 'Samoan Tālā', symbol: 'WS$' },
    XAF: { label: 'Central African CFA Franc', symbol: 'FCFA' },
    XAG: { label: 'Silver Ounce', symbol: 'oz t' },
    XAU: { label: 'Gold Ounce', symbol: 'oz t' },
    XBA: { label: 'European Composite Unit (EURCO)', symbol: 'EURCO' },
    XBB: { label: 'European Monetary Unit (E.M.U.-6)', symbol: 'E.M.U.-6' },
    XBC: { label: 'European Unit of Account 9 (E.U.A.-9)', symbol: 'E.U.A.-9' },
    XBD: { label: 'European Unit of Account 17 (E.U.A.-17)', symbol: 'E.U.A.-17' },
    XCD: { label: 'East Caribbean Dollar', symbol: '$' },
    XDR: { label: 'Special Drawing Rights', symbol: 'SDR' },
    XOF: { label: 'West African CFA Franc', symbol: 'FCFA' },
    XPD: { label: 'Palladium Ounce', symbol: 'oz t' },
    XPF: { label: 'CFP Franc', symbol: '₣' },
    XPT: { label: 'Platinum Ounce', symbol: 'oz t' },
    XTS: { label: 'Codes specifically reserved for testing purposes', symbol: 'XTS' },
    YER: { label: 'Yemeni Rial', symbol: '﷼' },
    ZAR: { label: 'South African Rand', symbol: 'R' },
    ZMW: { label: 'Zambian Kwacha', symbol: 'ZK' },
    ZWL: { label: 'Zimbabwean Dollar', symbol: 'Z$' }
};

export const defaultCurrencyMeta: CurrencyMeta = {
    label: 'Unknown Currency',
    symbol: '?'
};